In [ ]:
import numpy as np
a = np.arange(30).reshape(6, 5)
b = a +1
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Blue Rectangle


In [ ]:
b[2:4:,:2] 

array([[11, 12],
       [16, 17]])

Green Rectangle

In [ ]:
b1,b2,b3 = np.split(b,3)
b4= np.vstack([b1,b2])
b4[b4%4 ==0]

array([ 4,  8, 12, 16, 20])

Red Rectangle

In [ ]:
b5= np.vstack([b,b1])
b5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
b5[4:7, 3:] 

array([[24, 25],
       [29, 30],
       [ 4,  5]])