In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
# import dataset
path = '/content/gdrive/MyDrive/Data Pre Processing/Homework - Data Preprocessing.csv'
dataset = pd.read_csv(path, delimiter=',')
dataset

Animal   Age    Worth Friendly
0    Cat   NaN  72000.0       No
1    Dog  17.0      NaN      Yes
2  Moose   6.0  54000.0       No
3    NaN   8.0  61000.0       No
4  Moose   4.0      NaN      Yes
5    Cat  15.0  58000.0      Yes
6    Dog   NaN  52000.0       No
7    Cat  12.0      NaN      Yes
8  Moose   NaN  83000.0       No
9    Cat   7.0  67000.0      Yes

# melihat cuplikan dataset


In [ ]:
dataset.head()

Animal   Age    Worth Friendly
0    Cat   NaN  72000.0       No
1    Dog  17.0      NaN      Yes
2  Moose   6.0  54000.0       No
3    NaN   8.0  61000.0       No
4  Moose   4.0      NaN      Yes

##Duplicated Data

In [ ]:
dataset.duplicated(subset=['Animal', 'Friendly']).sum()

3

In [ ]:
# statistika deskriptif
dataset.describe()

Age         Worth
count   7.000000      7.000000
mean    9.857143  63857.142857
std     4.879500  10976.164652
min     4.000000  52000.000000
25%     6.500000  56000.000000
50%     8.000000  61000.000000
75%    13.500000  69500.000000
max    17.000000  83000.000000

In [ ]:
from collections import Counter
Counter(dataset["Animal"])

Counter({'Cat': 4, 'Dog': 2, 'Moose': 3, nan: 1})

In [ ]:
Counter(dataset["Friendly"])

Counter({'No': 5, 'Yes': 5})

In [ ]:
# dropping duplicate values
dataset = dataset.drop_duplicates()
dataset = dataset.reset_index(drop = True)

In [ ]:
dataset.describe()

Age         Worth
count   7.000000      7.000000
mean    9.857143  63857.142857
std     4.879500  10976.164652
min     4.000000  52000.000000
25%     6.500000  56000.000000
50%     8.000000  61000.000000
75%    13.500000  69500.000000
max    17.000000  83000.000000

In [ ]:
# checking for missing values
dataset.isnull()

Animal    Age  Worth  Friendly
0   False   True  False     False
1   False  False   True     False
2   False  False  False     False
3    True  False  False     False
4   False  False   True     False
5   False  False  False     False
6   False   True  False     False
7   False  False   True     False
8   False   True  False     False
9   False  False  False     False

In [ ]:
# Melihat kolom yang memiliki missing value
dataset[dataset.isnull().any(axis = 1)]

Animal   Age    Worth Friendly
0    Cat   NaN  72000.0       No
1    Dog  17.0      NaN      Yes
3    NaN   8.0  61000.0       No
4  Moose   4.0      NaN      Yes
6    Dog   NaN  52000.0       No
7    Cat  12.0      NaN      Yes
8  Moose   NaN  83000.0       No

In [ ]:
# checking the number of missing data
dataset.isnull().sum()

Animal      1
Age         3
Worth       3
Friendly    0
dtype: int64

## Dropping Data

In [ ]:
# Dropping data rows with missing values
dataset.dropna(how='any')

Animal   Age    Worth Friendly
2  Moose   6.0  54000.0       No
5    Cat  15.0  58000.0      Yes
9    Cat   7.0  67000.0      Yes

In [ ]:
# Dropping rows with missing values based on a columns
dataset.dropna(how='any', subset = ["Worth"])

Animal   Age    Worth Friendly
0    Cat   NaN  72000.0       No
2  Moose   6.0  54000.0       No
3    NaN   8.0  61000.0       No
5    Cat  15.0  58000.0      Yes
6    Dog   NaN  52000.0       No
8  Moose   NaN  83000.0       No
9    Cat   7.0  67000.0      Yes

#Imputing Missing Value

In [ ]:
# Imputing missing values on numerical features
print(dataset["Age"].mean())
print(dataset["Age"].fillna(dataset["Age"].mean()))

9.857142857142858
0     9.857143
1    17.000000
2     6.000000
3     8.000000
4     4.000000
5    15.000000
6     9.857143
7    12.000000
8     9.857143
9     7.000000
Name: Age, dtype: float64


In [ ]:
# Imputing missing values on numerical features
print(dataset["Worth"].median())
print(dataset["Worth"].fillna(dataset["Worth"].median()))

61000.0
0    72000.0
1    61000.0
2    54000.0
3    61000.0
4    61000.0
5    58000.0
6    52000.0
7    61000.0
8    83000.0
9    67000.0
Name: Worth, dtype: float64


In [ ]:
# Imputing missing values on numerical features
print(dataset["Animal"].mode())
print(dataset["Animal"].fillna(dataset["Animal"].mode()[0]))

0    Cat
dtype: object
0      Cat
1      Dog
2    Moose
3      Cat
4    Moose
5      Cat
6      Dog
7      Cat
8    Moose
9      Cat
Name: Animal, dtype: object


In [ ]:
# Mengisi missing value numerikal dengan mean 
dataset = dataset.fillna(dataset.mean())
# Kategorikal dengan mode
dataset["Animal"] = dataset["Animal"].fillna(dataset["Animal"].mode()[0])
# Hapus missing value pada target
dataset.dropna(subset = ["Friendly"], inplace = True) 

# Splitting dataset into independent and dependent variable


In [ ]:
X = dataset[['Animal', 'Age', 'Worth']].values
y = dataset['Friendly'].values
print(X)

[['Cat' 9.857142857142858 72000.0]
 ['Dog' 17.0 63857.142857142855]
 ['Moose' 6.0 54000.0]
 ['Cat' 8.0 61000.0]
 ['Moose' 4.0 63857.142857142855]
 ['Cat' 15.0 58000.0]
 ['Dog' 9.857142857142858 52000.0]
 ['Cat' 12.0 63857.142857142855]
 ['Moose' 9.857142857142858 83000.0]
 ['Cat' 7.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# replacing the missing values in the age and salary column with the mean


In [ ]:
# import the SimpleImputer class from the sklearn library
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X[:, 1:3])

[[9.857142857142858 72000.0]
 [17.0 63857.142857142855]
 [6.0 54000.0]
 [8.0 61000.0]
 [4.0 63857.142857142855]
 [15.0 58000.0]
 [9.857142857142858 52000.0]
 [12.0 63857.142857142855]
 [9.857142857142858 83000.0]
 [7.0 67000.0]]


# Handling Categorical Data


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 9.857142857142858 72000.0]
 [0.0 1.0 0.0 17.0 63857.142857142855]
 [0.0 0.0 1.0 6.0 54000.0]
 [1.0 0.0 0.0 8.0 61000.0]
 [0.0 0.0 1.0 4.0 63857.142857142855]
 [1.0 0.0 0.0 15.0 58000.0]
 [0.0 1.0 0.0 9.857142857142858 52000.0]
 [1.0 0.0 0.0 12.0 63857.142857142855]
 [0.0 0.0 1.0 9.857142857142858 83000.0]
 [1.0 0.0 0.0 7.0 67000.0]]


# Dummies (One hot encoding menggunakan pandas)


In [ ]:
pd.get_dummies(dataset.drop(columns = ["Friendly"]))

Age         Worth  Animal_Cat  Animal_Dog  Animal_Moose
0   9.857143  72000.000000           1           0             0
1  17.000000  63857.142857           0           1             0
2   6.000000  54000.000000           0           0             1
3   8.000000  61000.000000           1           0             0
4   4.000000  63857.142857           0           0             1
5  15.000000  58000.000000           1           0             0
6   9.857143  52000.000000           0           1             0
7  12.000000  63857.142857           1           0             0
8   9.857143  83000.000000           0           0             1
9   7.000000  67000.000000           1           0             0

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Encoding the target variable


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting Dataset into Training and Test Set


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 15.0 58000.0]
 [1.0 0.0 0.0 9.857142857142858 72000.0]
 [1.0 0.0 0.0 12.0 63857.142857142855]
 [0.0 0.0 1.0 6.0 54000.0]
 [1.0 0.0 0.0 8.0 61000.0]
 [0.0 1.0 0.0 9.857142857142858 52000.0]
 [1.0 0.0 0.0 7.0 67000.0]
 [0.0 0.0 1.0 9.857142857142858 83000.0]]


In [ ]:
print(X_test)

[[0.0 0.0 1.0 4.0 63857.142857142855]
 [0.0 1.0 0.0 17.0 63857.142857142855]]


In [ ]:
print(y_train)

[1 0 1 0 0 0 1 0]


In [ ]:
print(y_test)

[1 1]


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc = StandardScaler()
mm = MinMaxScaler()
sc.fit_transform(X_train)

array([[ 0.77459667, -0.37796447, -0.57735027,  1.98127723, -0.61617571],
       [ 0.77459667, -0.37796447, -0.57735027,  0.0600387 ,  0.85663452],
       [ 0.77459667, -0.37796447, -0.57735027,  0.86055476,  0.        ],
       [-1.29099445, -0.37796447,  1.73205081, -1.38089019, -1.03697863],
       [ 0.77459667, -0.37796447, -0.57735027, -0.63374188, -0.30057352],
       [-1.29099445,  2.64575131, -0.57735027,  0.0600387 , -1.24738009],
       [ 0.77459667, -0.37796447, -0.57735027, -1.00731604,  0.33063087],
       [-1.29099445, -0.37796447,  1.73205081,  0.0600387 ,  2.01384255]])

In [ ]:
mm.fit_transform(X_train)

array([[1.        , 0.        , 0.        , 1.        , 0.19354839],
       [1.        , 0.        , 0.        , 0.42857143, 0.64516129],
       [1.        , 0.        , 0.        , 0.66666667, 0.38248848],
       [0.        , 0.        , 1.        , 0.        , 0.06451613],
       [1.        , 0.        , 0.        , 0.22222222, 0.29032258],
       [0.        , 1.        , 0.        , 0.42857143, 0.        ],
       [1.        , 0.        , 0.        , 0.11111111, 0.48387097],
       [0.        , 0.        , 1.        , 0.42857143, 1.        ]])